-- Schema-only fixture of Journal's moments.sqlite (no personal data).
-- Extracted from a real store; used by tests/make-fixture.sh for CI runs
-- where no Journal library exists.

CREATE TABLE ZJOURNALENTRYASSETFILEATTACHMENTMO ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZINDEX INTEGER, ZISREMOVEDFROMCLOUD INTEGER, ZISUPLOADEDTOCLOUD INTEGER, ZNEEDSPROCESSING INTEGER, ZASSET INTEGER, ZFILEPATH VARCHAR, ZNAME VARCHAR, ZID BLOB, ZPARENTID BLOB, ZRECORDSYSTEMFIELDS BLOB );

CREATE TABLE ZJOURNALENTRYASSETMO ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZISBEINGEDITED INTEGER, ZISFULLYREMOVED INTEGER, ZISHIDDEN INTEGER, ZISREMOVEDFROMCLOUD INTEGER, ZISSLIM INTEGER, ZISUNDOABLYDELETED INTEGER, ZISUPLOADEDTOCLOUD INTEGER, ZMINIMUMSUPPORTEDAPPVERSION INTEGER, ZREFRESHASSETMETADATA INTEGER, ZENTRY INTEGER, ZCREATEDDATE TIMESTAMP, ZSUGGESTIONDATE TIMESTAMP, ZASSETTYPE VARCHAR, ZCONTENTTYPE VARCHAR, ZFILEATTACHMENT VARCHAR, ZOSVERSION VARCHAR, ZSOURCE VARCHAR, ZID BLOB, ZPARENTID BLOB, ZSUGGESTIONID BLOB, ZASSETMETADATA BLOB, ZRECORDSYSTEMFIELDS BLOB, ZTITLE BLOB );

CREATE TABLE ZJOURNALENTRYMO ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZFLAGGED INTEGER, ZISDRAFT INTEGER, ZISFULLYREMOVED INTEGER, ZISREMOVEDFROMCLOUD INTEGER, ZISTIP INTEGER, ZISUPLOADEDTOCLOUD INTEGER, ZMINIMUMSUPPORTEDAPPVERSION INTEGER, ZMINIMUMSUPPORTEDAPPVERSIONMODE INTEGER, ZRECENTLYDELETED INTEGER, ZSHOWPHOTOMEMORYBANNER INTEGER, ZSHOWTITLE INTEGER, ZTEXTLENGTH INTEGER, ZBUNDLEDATE TIMESTAMP, ZBUNDLEENDDATE TIMESTAMP, ZCREATEDDATE TIMESTAMP, ZDELETEDONDATE TIMESTAMP, ZENTRYDATAUPDATEDATE TIMESTAMP, ZENTRYDATE TIMESTAMP, ZMOMENTDATEFORSORTING TIMESTAMP, ZRECENTLYDELETEDENTRYDATE TIMESTAMP, ZUPDATEDDATE TIMESTAMP, ZDATESOURCE VARCHAR, ZENTRYTYPE VARCHAR, ZREFLECTIONTYPE VARCHAR, ZBUNDLEID BLOB, ZID BLOB, ZMERGEABLEATTRIBUTES BLOB, ZASSETORDERING BLOB, ZPROMPT BLOB, ZRECORDSYSTEMFIELDS BLOB, ZREFLECTIONICON BLOB, ZREFLECTIONPROMPT BLOB, ZTEXT BLOB, ZTITLE BLOB );

CREATE TABLE Z_5JOURNALS ( Z_5ENTRIES INTEGER, Z_6JOURNALS INTEGER, PRIMARY KEY (Z_5ENTRIES, Z_6JOURNALS) );

CREATE TABLE ZJOURNALMO ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZISUPLOADEDTOCLOUD INTEGER, ZSORTCATEGORY INTEGER, ZSORTORDER INTEGER, ZUSERDELETED INTEGER, ZCREATEDDATE TIMESTAMP, ZUPDATEDDATE TIMESTAMP, ZID BLOB, ZMERGEABLEATTRIBUTES BLOB, ZRECORDSYSTEMFIELDS BLOB );

CREATE TABLE Z_PRIMARYKEY (Z_ENT INTEGER PRIMARY KEY, Z_NAME VARCHAR, Z_SUPER INTEGER, Z_MAX INTEGER);

CREATE TABLE Z_METADATA (Z_VERSION INTEGER PRIMARY KEY, Z_UUID VARCHAR(255), Z_PLIST BLOB);
